export const USER_GET_USER_REQUEST = 'USER_GET_USER_REQUEST';
export const USER_GET_USER_SUCCESS = 'USER_GET_USER_SUCCESS';
export const USER_GET_USER_FAILURE = 'USER_GET_USER_FAILURE';

export const USER_GET_USER_INFO_REQUEST = 'USER_GET_USER_INFO_REQUEST';
export const USER_GET_USER_INFO_SUCCESS = 'USER_GET_USER_INFO_SUCCESS';
export const USER_GET_USER_INFO_FAILURE = 'USER_GET_USER_INFO_FAILURE';

export const USER_UPDATE_USER_REQUEST = 'USER_UPDATE_USER_REQUEST';
export const USER_UPDATE_USER_SUCCESS = 'USER_UPDATE_USER_SUCCESS';
export const USER_UPDATE_USER_FAILURE = 'USER_UPDATE_USER_FAILURE';

export const USER_SWITCH_TO_EDITION_MODE = 'USER_SWITCH_TO_EDITION_MODE';
export const USER_SWITCH_TO_READ_MODE = 'USER_SWITCH_TO_READ_MODE';
