export const LEDGER_FORM_INIT_FORM = 'LEDGER_FORM_INIT_FORM';
export const LEDGER_FORM_INIT_FORM_DONE = 'LEDGER_FORM_INIT_FORM_DONE';
export const LEDGER_FORM_UPDATE = 'LEDGER_FORM_UPDATE';
export const LEDGER_FORM_UPDATE_DONE = 'LEDGER_FORM_UPDATE_DONE';
export const LEDGER_FORM_SUBMIT = 'LEDGER_FORM_SUBMIT';