export const ACCOUNT_FORM_INIT_FORM = 'ACCOUNT_FORM_INIT_FORM';
export const ACCOUNT_FORM_INIT_FORM_DONE = 'ACCOUNT_FORM_INIT_FORM_DONE';
export const ACCOUNT_FORM_UPDATE = 'ACCOUNT_FORM_UPDATE';
export const ACCOUNT_FORM_UPDATE_DONE = 'ACCOUNT_FORM_UPDATE_DONE';
export const ACCOUNT_FORM_SUBMIT = 'ACCOUNT_FORM_SUBMIT';