export const USER_FORM_INIT_FORM = 'USER_FORM_INIT_FORM';
export const USER_FORM_INIT_FORM_DONE = 'USER_FORM_INIT_FORM_DONE';
export const USER_FORM_UPDATE = 'USER_FORM_UPDATE';
export const USER_FORM_UPDATE_DONE = 'USER_FORM_UPDATE_DONE';
export const USER_FORM_SUBMIT = 'USER_FORM_SUBMIT';
