// Load ledgers.
export const LEDGER_LIST_REQUEST = 'LEDGER_LIST_REQUEST';
export const LEDGER_LIST_SUCCESS = 'LEDGER_LIST_SUCCESS';
export const LEDGER_LIST_FAILURE = 'LEDGER_LIST_FAILURE';

// Create a ledger.
export const LEDGER_CREATE_REQUEST = 'LEDGER_CREATE_REQUEST';
export const LEDGER_CREATE_SUCCESS = 'LEDGER_CREATE_SUCCESS';
export const LEDGER_CREATE_FAILURE = 'LEDGER_CREATE_FAILURE';

// Update ledger.
export const LEDGER_UPDATE_REQUEST = 'LEDGER_UPDATE_REQUEST';
export const LEDGER_UPDATE_SUCCESS = 'LEDGER_UPDATE_SUCCESS';
export const LEDGER_UPDATE_FAILURE = 'LEDGER_UPDATE_FAILURE';

// Delete ledger.
export const LEDGER_DELETE_REQUEST = 'LEDGER_DELETE_REQUEST';
export const LEDGER_DELETE_SUCCESS = 'LEDGER_DELETE_SUCCESS';
export const LEDGER_DELETE_FAILURE = 'LEDGER_DELETE_FAILURE';

// Switch to create.
export const LEDGER_SWITCH_CREATION = 'LEDGER_SWITCH_CREATION';

// Select a ledger.
export const LEDGER_SELECT = 'LEDGER_SELECT';
