// Load movement list.
export const MOVEMENT_LIST_REQUEST = 'MOVEMENT_LIST_REQUEST';
export const MOVEMENT_LIST_SUCCESS = 'MOVEMENT_LIST_SUCCESS';
export const MOVEMENT_LIST_FAILURE = 'MOVEMENT_LIST_FAILURE';

// Create movement.
export const MOVEMENT_CREATE_REQUEST = 'MOVEMENT_CREATE_REQUEST';
export const MOVEMENT_CREATE_SUCCESS = 'MOVEMENT_CREATE_SUCCESS';
export const MOVEMENT_CREATE_FAILURE = 'MOVEMENT_CREATE_FAILURE';

// Update movement.
export const MOVEMENT_UPDATE_REQUEST = 'MOVEMENT_UPDATE_REQUEST';
export const MOVEMENT_UPDATE_SUCCESS = 'MOVEMENT_UPDATE_SUCCESS';
export const MOVEMENT_UPDATE_FAILURE = 'MOVEMENT_UPDATE_FAILURE';

// Delete movement.
export const MOVEMENT_DELETE_REQUEST = 'MOVEMENT_DELETE_REQUEST';
export const MOVEMENT_DELETE_SUCCESS = 'MOVEMENT_DELETE_SUCCESS';
export const MOVEMENT_DELETE_FAILURE = 'MOVEMENT_DELETE_FAILURE';

// Select a movement.
export const MOVEMENT_SELECT = 'MOVEMENT_SELECT';

// Init a movement.
export const MOVEMENT_INIT = 'MOVEMENT_INIT';
export const MOVEMENT_INIT_DONE = 'MOVEMENT_INIT_DONE';
